version: "3.9"

#########################
# Networks              #
#########################
networks:
  traefik-net:
    external: true
  gluetun-net:
    driver: bridge

#########################
# Services              #
#########################
services:
  #########################
  # VPN (Gluetun)
  #########################
  gluetun:
    image: qmcgaw/gluetun
    container_name: gluetun
    cap_add:
      - NET_ADMIN
    devices:
      - /dev/net/tun
    environment:
      - VPN_SERVICE_PROVIDER=custom
      - OPENVPN_USER=${VPN_USER}
      - OPENVPN_PASSWORD=${VPN_PASSWORD}
      - TZ=Europe/Prague
    volumes:
      - /Users/martinargalas/docker/gluetun:/gluetun
    ports:
      - "8080:8080"       # qBittorrent web UI
      - "8081:8081"       # Sabnzbd web UI
      - "8989:8989"       # Sonarr
      - "7878:7878"       # Radarr
      - "9696:9696"       # Prowlarr
    networks:
      - gluetun-net
      - traefik-net
    restart: unless-stopped

  #########################
  # Sonarr
  #########################
  sonarr:
    image: linuxserver/sonarr
    container_name: sonarr
    network_mode: "service:gluetun"
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Europe/Prague
    volumes:
      - /Users/martinargalas/docker/sonarr:/config
      - /Volumes/Data/media:/media
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.sonarr.rule=Host(`sonarr.lab`)"
      - "traefik.http.services.sonarr.loadbalancer.server.port=8989"
    depends_on:
      - gluetun
    restart: unless-stopped

  #########################
  # Radarr
  #########################
  radarr:
    image: linuxserver/radarr
    container_name: radarr
    network_mode: "service:gluetun"
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Europe/Prague
    volumes:
      - /Users/martinargalas/docker/radarr:/config
      - /Volumes/Data/media:/media
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.radarr.rule=Host(`radarr.lab`)"
      - "traefik.http.services.radarr.loadbalancer.server.port=7878"
    depends_on:
      - gluetun
    restart: unless-stopped

  #########################
  # Sabnzbd
  #########################
  sabnzbd:
    image: linuxserver/sabnzbd
    container_name: sabnzbd
    network_mode: "service:gluetun"
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Europe/Prague
    volumes:
      - /Users/martinargalas/docker/sabnzbd:/config
      - /Volumes/Data/downloads:/downloads
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.sabnzbd.rule=Host(`sabnzbd.lab`)"
      - "traefik.http.services.sabnzbd.loadbalancer.server.port=8081"
    depends_on:
      - gluetun
    restart: unless-stopped

  #########################
  # Prowlarr
  #########################
  prowlarr:
    image: linuxserver/prowlarr
    container_name: prowlarr
    network_mode: "service:gluetun"
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Europe/Prague
    volumes:
      - /Users/martinargalas/docker/prowlarr:/config
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.prowlarr.rule=Host(`prowlarr.lab`)"
      - "traefik.http.services.prowlarr.loadbalancer.server.port=9696"
    depends_on:
      - gluetun
    restart: unless-stopped

  #########################
  # Pi-hole
  #########################
  pihole:
    image: pihole/pihole:latest
    container_name: pihole
    hostname: pihole
    environment:
      - TZ=Europe/Prague
      - WEBPASSWORD=admin
    volumes:
      - /Users/martinargalas/docker/pihole/etc-pihole:/etc/pihole
      - /Users/martinargalas/docker/pihole/etc-dnsmasq.d:/etc/dnsmasq.d
    networks:
      - traefik-net
    ports:
      - "53:53/tcp"
      - "53:53/udp"
      - "8082:80" # pihole web UI
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.pihole.rule=Host(`pihole.lab`)"
      - "traefik.http.services.pihole.loadbalancer.server.port=80"
    restart: unless-stopped
